### ISSUE TITLE
practica 1_ expresiones boleanas 

### ISSUE THREAD

**Issue by yaritzaov123** [SistemasTecTlaxiaco/expresiones-boolenas-equipo-julio-cesar-gonzalez-lopez#1]
[EXPREXIONES BOLEANAS.pdf](https://github.com/SistemasTecTlaxiaco/expresiones-boolenas-equipo-julio-cesar-gonzalez-lopez/files/7729585/EXPREXIONES.BOLEANAS.pdf)

**Comment by isaireyesp1** [comment]
Portada: 25%
Procedimiento: 25%
Figuras, ilustraciones y fotografías.: 25%
Resultados y conclusiones: 25%
resultados: 100%
R : 30%
Calificado por isai reyes peña

**Comment by josealfredo79** [comment]
Bien hecho y revisado
